theme: jekyll-theme-cayman
header: ![Image](https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=747&q=80
title: CIT Minor Portfolio
description: display work from all CIT classes
